hetzner-server-delete:
  hcloud server delete server-a

hetzner-server-create:
  hcloud server create \
      --image ubuntu-24.04 \
      --name server-a \
      --ssh-key user-a \
      --type cx23 \
      --location nbg1 \
      --user-data-from-file ./user_data.yaml

export TMP_HOST_DIR := `echo $(mktemp -d)`
install-nixos SERVER_USER SERVER_IPV4 USER_A_PRIVATE_SSH_KEY_PATH:
  @echo Initializing a temporary directory "${TMP_HOST_DIR}/etc/ssh"
  # 1. Create a temporary directory for the files we want to move to the server.
  mkdir -p $TMP_HOST_DIR/persist/secrets

  @echo Decrypting and copying disk key to "${TMP_HOST_DIR}/persist/secrets/disk-key"
  # 2. Decrypt and copy server-a's disk key
  sops decrypt --extract '["disk-key"]' hosts/server-a/secrets/init.yaml > $TMP_HOST_DIR/persist/secrets/disk-key

  @echo Installing NixOS "{{ SERVER_USER }}@{{ SERVER_IPV4 }}"
  # Run the installation
  nix run github:nix-community/nixos-anywhere -- \
        --flake .#server-a --target-host {{ SERVER_USER }}@{{ SERVER_IPV4 }} \
        -i {{ USER_A_PRIVATE_SSH_KEY_PATH }} \
        --extra-files $TMP_HOST_DIR \
        --build-on local \
        --generate-hardware-config nixos-generate-config ./modules/hetzner/hardware-configuration.nix \
        --disk-encryption-keys /persist/secrets/disk-key "$TMP_HOST_DIR/persist/secrets/disk-key"
